// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetApiV1HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetApiV1HealthResponses = {
    /**
     * OK
     */
    200: {
        success?: boolean;
        data?: {
            status?: string;
            version?: string;
            service?: string;
            contractAddress?: string;
            chainId?: number;
        };
    };
};

export type GetApiV1HealthResponse = GetApiV1HealthResponses[keyof GetApiV1HealthResponses];

export type GetApiV1MarketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/market';
};

export type GetApiV1MarketResponses = {
    /**
     * OK
     */
    200: {
        success?: boolean;
        data?: {
            usycPrice?: string;
            contractAddress?: string;
            chainId?: number;
            chainName?: string;
        };
    };
};

export type GetApiV1MarketResponse = GetApiV1MarketResponses[keyof GetApiV1MarketResponses];

export type GetApiV1PositionsByAddressData = {
    body?: never;
    path: {
        address: string;
    };
    query?: never;
    url: '/api/v1/positions/{address}';
};

export type GetApiV1PositionsByAddressErrors = {
    /**
     * Invalid address
     */
    400: unknown;
};

export type GetApiV1PositionsByAddressResponses = {
    /**
     * OK
     */
    200: {
        success?: boolean;
        data?: {
            address?: string;
            usycPrice?: string;
            position?: {
                usycDeposited?: string;
                usdcBorrowed?: string;
                ltvBps?: number;
                active?: boolean;
            } | null;
        };
    };
};

export type GetApiV1PositionsByAddressResponse = GetApiV1PositionsByAddressResponses[keyof GetApiV1PositionsByAddressResponses];

export type GetApiV1PositionsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Comma-separated list of 0x addresses
         */
        addresses: string;
    };
    url: '/api/v1/positions';
};

export type GetApiV1PositionsErrors = {
    /**
     * Missing or invalid addresses
     */
    400: unknown;
};

export type GetApiV1PositionsResponses = {
    /**
     * OK
     */
    200: {
        success?: boolean;
        data?: {
            usycPrice?: string;
            positions?: Array<{
                address?: string;
                position?: {
                    usycDeposited?: string;
                    usdcBorrowed?: string;
                    ltvBps?: number;
                    active?: boolean;
                } | null;
            }>;
        };
    };
};

export type GetApiV1PositionsResponse = GetApiV1PositionsResponses[keyof GetApiV1PositionsResponses];

export type GetApiV1AgentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agent';
};

export type GetApiV1AgentResponses = {
    /**
     * OK
     */
    200: {
        success?: boolean;
        data?: {
            running?: boolean;
            contractAddress?: string | null;
            watchedAddressesCount?: number | null;
        };
    };
};

export type GetApiV1AgentResponse = GetApiV1AgentResponses[keyof GetApiV1AgentResponses];

export type GetApiV1MonitoringHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/monitoring/health';
};

export type GetApiV1MonitoringHealthErrors = {
    /**
     * One or more checks failed (degraded)
     */
    503: unknown;
};

export type GetApiV1MonitoringHealthResponses = {
    /**
     * All checks passed
     */
    200: unknown;
};

export type GetApiV1MonitoringReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/monitoring/ready';
};

export type GetApiV1MonitoringReadyErrors = {
    /**
     * Not ready
     */
    503: unknown;
};

export type GetApiV1MonitoringReadyResponses = {
    /**
     * Ready to accept traffic
     */
    200: unknown;
};

export type GetApiV1MonitoringStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/monitoring/status';
};

export type GetApiV1MonitoringStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AnalyticsOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/analytics/overview';
};

export type GetApiV1AnalyticsOverviewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AnalyticsWebhooksData = {
    body?: never;
    path?: never;
    query?: {
        hours?: number;
    };
    url: '/api/v1/analytics/webhooks';
};

export type GetApiV1AnalyticsWebhooksResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AnalyticsUsageData = {
    body?: never;
    path?: never;
    query?: {
        days?: number;
    };
    url: '/api/v1/analytics/usage';
};

export type GetApiV1AnalyticsUsageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1AlertsStatusData = {
    body?: never;
    path?: never;
    query: {
        address: string;
    };
    url: '/api/v1/alerts/status';
};

export type GetApiV1AlertsStatusErrors = {
    /**
     * Invalid address
     */
    400: unknown;
};

export type GetApiV1AlertsStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AlertsRegisterData = {
    body?: {
        address: string;
        phone: string;
        preferences?: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/v1/alerts/register';
};

export type PostApiV1AlertsRegisterErrors = {
    /**
     * Invalid input
     */
    400: unknown;
};

export type PostApiV1AlertsRegisterResponses = {
    /**
     * Registered
     */
    200: unknown;
};

export type PostApiV1AlertsPreferencesData = {
    body?: {
        address: string;
        preferences: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/api/v1/alerts/preferences';
};

export type PostApiV1AlertsPreferencesErrors = {
    /**
     * Not registered
     */
    404: unknown;
};

export type PostApiV1AlertsPreferencesResponses = {
    /**
     * Updated
     */
    200: unknown;
};

export type PostApiV1AlertsTestData = {
    body?: {
        address: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/alerts/test';
};

export type PostApiV1AlertsTestErrors = {
    /**
     * Not registered
     */
    404: unknown;
};

export type PostApiV1AlertsTestResponses = {
    /**
     * Sent or error in body
     */
    200: unknown;
};

export type GetApiV1OpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/openapi.json';
};

export type GetApiV1OpenapiJsonResponses = {
    /**
     * OpenAPI 3.0 JSON
     */
    200: unknown;
};

export type GetApiV1AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetApiV1AuthMeErrors = {
    /**
     * Missing or invalid API key
     */
    401: unknown;
};

export type GetApiV1AuthMeResponses = {
    /**
     * OK
     */
    200: {
        success?: boolean;
        data?: {
            user_address?: string;
            permissions?: string;
            rate_limit?: number;
            name?: string;
        };
    };
};

export type GetApiV1AuthMeResponse = GetApiV1AuthMeResponses[keyof GetApiV1AuthMeResponses];

export type GetApiV1AuthKeysData = {
    body?: never;
    path?: never;
    query: {
        address: string;
    };
    url: '/api/v1/auth/keys';
};

export type GetApiV1AuthKeysErrors = {
    /**
     * Invalid or missing address
     */
    400: unknown;
};

export type GetApiV1AuthKeysResponses = {
    /**
     * OK
     */
    200: {
        success?: boolean;
        data?: {
            keys?: Array<{
                id?: string;
                name?: string;
                user_address?: string;
                permissions?: string;
                rate_limit?: number;
                created_at?: string;
                last_used?: string | null;
                expires_at?: string | null;
            }>;
        };
    };
};

export type GetApiV1AuthKeysResponse = GetApiV1AuthKeysResponses[keyof GetApiV1AuthKeysResponses];

export type PostApiV1AuthKeysData = {
    body?: {
        name?: string;
        user_address: string;
        permissions?: string;
        rate_limit?: number;
        expires_at?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/keys';
};

export type PostApiV1AuthKeysErrors = {
    /**
     * Invalid or missing user_address
     */
    400: unknown;
};

export type PostApiV1AuthKeysResponses = {
    /**
     * Created
     */
    201: {
        success?: boolean;
        data?: {
            id?: string;
            /**
             * Store securely; not returned again
             */
            rawKey?: string;
            name?: string;
            user_address?: string;
            permissions?: string;
            rate_limit?: number;
            created_at?: string;
        };
    };
};

export type PostApiV1AuthKeysResponse = PostApiV1AuthKeysResponses[keyof PostApiV1AuthKeysResponses];

export type DeleteApiV1AuthKeysByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        address: string;
    };
    url: '/api/v1/auth/keys/{id}';
};

export type DeleteApiV1AuthKeysByIdErrors = {
    /**
     * Invalid or missing address
     */
    400: unknown;
    /**
     * Key not found or not owned by address
     */
    404: unknown;
};

export type DeleteApiV1AuthKeysByIdResponses = {
    /**
     * Revoked
     */
    200: unknown;
};

export type GetApiV1WebhooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks';
};

export type GetApiV1WebhooksErrors = {
    /**
     * Invalid API key
     */
    401: unknown;
};

export type GetApiV1WebhooksResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1WebhooksData = {
    body?: {
        url: string;
        events: Array<'rebalance' | 'warning' | 'price'>;
        /**
         * Optional; generated if omitted
         */
        secret?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhooks';
};

export type PostApiV1WebhooksErrors = {
    /**
     * Invalid url or events
     */
    400: unknown;
    /**
     * Invalid API key
     */
    401: unknown;
};

export type PostApiV1WebhooksResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteApiV1WebhooksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/webhooks/{id}';
};

export type DeleteApiV1WebhooksByIdErrors = {
    /**
     * Invalid API key
     */
    401: unknown;
    /**
     * Webhook not found
     */
    404: unknown;
};

export type DeleteApiV1WebhooksByIdResponses = {
    /**
     * Deleted
     */
    200: unknown;
};

export type GetApiV1WebhooksByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/webhooks/{id}';
};

export type GetApiV1WebhooksByIdErrors = {
    /**
     * Invalid API key
     */
    401: unknown;
    /**
     * Webhook not found
     */
    404: unknown;
};

export type GetApiV1WebhooksByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiV1WebhooksByIdData = {
    body?: {
        url?: string;
        events?: Array<'rebalance' | 'warning' | 'price'>;
        active?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/webhooks/{id}';
};

export type PatchApiV1WebhooksByIdErrors = {
    /**
     * Invalid API key
     */
    401: unknown;
    /**
     * Webhook not found
     */
    404: unknown;
};

export type PatchApiV1WebhooksByIdResponses = {
    /**
     * Updated
     */
    200: unknown;
};

export type GetApiV1WebhooksByIdDeliveriesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
    };
    url: '/api/v1/webhooks/{id}/deliveries';
};

export type GetApiV1WebhooksByIdDeliveriesErrors = {
    /**
     * Invalid API key
     */
    401: unknown;
    /**
     * Webhook not found
     */
    404: unknown;
};

export type GetApiV1WebhooksByIdDeliveriesResponses = {
    /**
     * OK
     */
    200: unknown;
};
